DROP DATABASE IF EXISTS banco_teste;
CREATE DATABASE banco_teste;

USE banco_teste;

CREATE TABLE usuario (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(153) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL
);

CREATE TABLE posts (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(100) NOT NULL,
conteudo VARCHAR(200) NOT NULL,
id_usuario INTEGER, 
FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);